# Generated by Django 5.0.7 on 2025-05-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_of_machine', models.CharField(max_length=255, verbose_name='Зав. № машины')),
                ('serial_number_of_engine', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('serial_number_of_transmission', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('serial_number_of_drive_axle', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('serial_number_of_steering_axle', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('supply_contract_number_and_date', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('date_shipped_from_factory', models.DateField(null=True, verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки (эксплуатации)')),
                ('equipment', models.CharField(blank=True, max_length=255, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('model_of_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enginemodel', verbose_name='Модель двигателя')),
                ('model_of_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentmodel', verbose_name='Модель техники')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(null=True)),
                ('operating_time', models.IntegerField()),
                ('work_order_number', models.CharField(max_length=255)),
                ('work_order_date', models.DateField(null=True)),
                ('the_organization_that_carried_out_the_maintenance', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintenancetype')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(null=True)),
                ('operating_time', models.IntegerField()),
                ('description_of_failure', models.CharField(max_length=255)),
                ('parts_used', models.CharField(max_length=255)),
                ('recovery_date', models.DateField(null=True)),
                ('equipment_downtime', models.IntegerField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.failurenode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
