# Generated by Django 5.0.7 on 2025-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_complaint_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheOrganizationThatCarriedOutTheMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
