# Generated by Django 5.0.7 on 2025-05-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theorganizationthatcarriedoutthemaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='the_organization_that_carried_out_the_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theorganizationthatcarriedoutthemaintenance', verbose_name='Организация, проводившая ТО'),
        ),
    ]
