# Generated by Django 5.0.7 on 2025-05-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maintenance_the_organization_that_carried_out_the_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
