from django.urls import path

from .views import (
    unauthorized_index,
    machine_list,
    machine_detail,
    MachineCreateView,
    MachineUpdateView,
    machine_delete,
    maintenance_list,
    MaintenanceCreateView,
    MaintenanceUpdateView,
    maintenance_delete,
    complaints_list,
    ComplaintCreateView,
    ComplaintUpdateView,
    complaint_delete,
    equipment_model_info,
    engine_model_info,
    transmission_model_info,
    drive_axle_model_info,
    steering_axle_model_info,
    client_info,
    service_company_info,
    maintenance_type_info,
    failure_node_info,
    recovery_method_info,
    the_organization_that_carried_out_the_maintenance_info,
)

urlpatterns = [
    path('', unauthorized_index, name='welcome'),
    path('machines/', machine_list, name='machine_list'),
    path('machines/create/', MachineCreateView.as_view(), name='machine_create'),
    path('machines/update/<int:pk>/', MachineUpdateView.as_view(), name='machine_update'),
    path('machines/delete/<int:machine_id>/', machine_delete, name='machine_delete'),
    path('machines/<int:machine_id>/', machine_detail, name='machine_detail'),
    path('maintenances/', maintenance_list, name='maintenance_list'),
    path('maintenances/create/', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('maintenances/update/<int:pk>/', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('maintenances/delete/<int:maintenance_id>/', maintenance_delete, name='maintenance_delete'),
    path('complaints/', complaints_list, name='complaints_list'),
    path('complaints/create/', ComplaintCreateView.as_view(), name='complaint_create'),
    path('complaints/update/<int:pk>/', ComplaintUpdateView.as_view(), name='complaint_update'),
    path('complaints/delete/<int:complaint_id>/', complaint_delete, name='complaint_delete'),

    path('machines/equipment_model_info/<int:equipment_model_id>/', equipment_model_info, name='equipment_model_info'),
    path('machines/engine_model_info/<int:engine_model_id>/', engine_model_info, name='engine_model_info'),
    path('machines/transmission_model_info/<int:transmission_model_id>/', transmission_model_info, name='transmission_model_info'),
    path('machines/drive_axle_model_info/<int:drive_axle_model_id>/', drive_axle_model_info, name='drive_axle_model_info'),
    path('machines/steering_axle_model_info/<int:steering_axle_model_id>/', steering_axle_model_info, name='steering_axle_model_info'),
    path('machines/client_info/<int:client_id>/', client_info, name='client_info'),
    path('machines/service_company_info/<int:service_company_id>/', service_company_info, name='service_company_info'),

    path('maintenances/maintenance_type_info/<int:maintenance_type_id>/', maintenance_type_info, name='maintenance_type_info'),
    path('maintenances/service_company_maintenance_info/<int:service_company_id>/', service_company_info, name='service_company_info'),
    path('maintenances/the_organization_that_carried_out_the_maintenance_info/<int:organization_id>/', the_organization_that_carried_out_the_maintenance_info, name='the_organization_that_carried_out_the_maintenance_info'),

    path('complaints/failure_node_info/<int:failure_node_id>/', failure_node_info, name='failure_node_info'),
    path('complaints/recovery_method_info/<int:recovery_method_id>/', recovery_method_info, name='recovery_method_info'),
    path('complaints/service_company_complaint_info/<int:service_company_id>/', service_company_info, name='service_company_info'),
]